insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (1,'Brasil','Brazil','BR',1058)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (2,'Afeganistão','Afghanistan','AF',132)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (3,'Albânia',' Republica da','Albania','AL',175)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (4,'Argélia','Algeria','DZ',590)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (5,'Samoa Americana','American Samoa','AS',6912)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (6,'Andorra','Andorra','AD',370)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (7,'Angola','Angola','AO',400)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (8,'Anguilla','Anguilla','AI',418)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (9,'Antártida','Antarctica','AQ',3596)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (10,'Antigua e Barbuda','Antigua and Barbuda','AG',434)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (11,'Argentina','Argentina','AR',639)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (12,'Armênia',' Republica da','Armenia','AM',647)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (13,'Aruba','Aruba','AW',655)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (14,'Austrália','Australia','AU',698)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (15,'Áustria','Austria','AT',728)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (16,'Azerbaijão',' Republica do','Azerbaijan','AZ',736)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (17,'Bahamas',' Ilhas','Bahamas','BS',779)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (18,'Bahrein',' Ilhas','Bahrain','BH',809)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (19,'Bangladesh','Bangladesh','BD',817)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (20,'Barbados','Barbados','BB',833)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (21,'Belarus',' Republica da','Belarus','BY',850)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (22,'Bélgica','Belgium','BE',876)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (23,'Belize','Belize','BZ',884)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (24,'Benin','Benin','BJ',2291)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (25,'Bermudas','Bermuda','BM',906)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (26,'Butão','Bhutan','BT',1198)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (27,'Bolívia','Bolivia','BO',973)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (28,'Bósnia-herzegovina (Republica da)','Bosnia and Herzegowina','BA',981)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (29,'Botsuana','Botswana','BW',1015)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (30,'Bouvet',' Ilha','Bouvet Island','BV',1023)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (31,'Território Britânico do Oceano Indico','British Indian Ocean Territory','IO',7820)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (32,'Brunei','Brunei Darussalam','BN',1082)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (33,'Bulgária',' Republica da','Bulgaria','BG',1112)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (34,'Burkina Faso','Burkina Faso','BF',310)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (35,'Burundi','Burundi','BI',1155)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (36,'Camboja','Cambodia','KH',1414)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (37,'Camarões','Cameroon','CM',1457)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (38,'Canada','Canada','CA',1490)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (39,'Cabo Verde',' Republica de','Cape Verde','CV',1279)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (40,'Cayman',' Ilhas','Cayman Islands','KY',1376)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (41,'Republica Centro-Africana','Central African Republic','CF',6408)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (42,'Chade','Chad','TD',7889)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (43,'Chile','Chile','CL',1589)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (44,'China',' Republica Popular','China','CN',1600)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (45,'Christmas',' Ilha (Navidad)','Christmas Island','CX',5118)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (46,'Cocos (Keeling) Ilhas','Cocos (Keeling) Islands','CC',1651)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (47,'Colômbia','Colombia','CO',1694)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (48,'Comores',' Ilhas','Comoros','KM',1732)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (49,'Congo','Congo','CG',1775)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (50,'Congo',' Republica Democrática do','Congo',' the Democratic Republic of the','CD',8885)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (51,'Cook',' Ilhas','Cook Islands','CK',1830)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (52,'Costa Rica','Costa Rica','CR',1961)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (53,'Costa do Marfim','Cote dIvoire','CI',1937)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (54,'Croácia (Republica da)','Croatia (Hrvatska)','HR',1953)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (55,'Cuba','Cuba','CU',1996)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (56,'Chipre','Cyprus','CY',1635)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (57,'Tcheca',' Republica','Czech Republic','CZ',7919)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (58,'Dinamarca','Denmark','DK',2321)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (59,'Djibuti','Djibouti','DJ',7838)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (60,'Dominica',' Ilha','Dominica','DM',2356)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (61,'Republica Dominicana','Dominican Republic','DO',6475)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (62,'Timor Leste','East Timor','TL',7951)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (63,'Equador','Ecuador','EC',2399)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (64,'Egito','Egypt','EG',2402)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (65,'El Salvador','El Salvador','SV',6874)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (66,'Guine-Equatorial','Equatorial Guinea','GQ',3310)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (67,'Eritreia','Eritrea','ER',2437)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (68,'Estônia',' Republica da','Estonia','EE',2518)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (69,'Etiópia','Ethiopia','ET',2534)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (70,'Falkland (Ilhas Malvinas)','Falkland Islands (Malvinas)','FK',2550)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (71,'Feroe',' Ilhas','Faroe Islands','FO',2593)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (72,'Fiji','Fiji','FJ',8702)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (73,'Finlândia','Finland','FI',2712)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (74,'Franca','France','FR',2755)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (76,'Guiana francesa','French Guiana','GF',3255)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (77,'Polinésia Francesa','French Polynesia','PF',5991)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (78,'Terras Austrais e Antárticas Francesas','French Southern Territories','TF',3607)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (79,'Gabão','Gabon','GA',2810)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (80,'Gambia','Gambia','GM',2852)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (81,'Georgia',' Republica da','Georgia','GE',2917)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (82,'Alemanha','Germany','DE',230)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (83,'Gana','Ghana','GH',2895)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (84,'Gibraltar','Gibraltar','GI',2933)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (85,'Grécia','Greece','GR',3018)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (86,'Groenlândia','Greenland','GL',3050)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (87,'Granada','Grenada','GD',2976)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (88,'Guadalupe','Guadeloupe','GP',3093)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (89,'Guam','Guam','GU',3131)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (90,'Guatemala','Guatemala','GT',3174)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (91,'Guine','Guinea','GN',3298)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (92,'Guine-Bissau','Guinea-Bissau','GW',3344)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (93,'Guiana','Guyana','GY',3379)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (94,'Haiti','Haiti','HT',3417)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (95,'Ilha Heard e Ilhas McDonald','Heard and Mc Donald Islands','HM',3603)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (96,'Vaticano',' Estado da Cidade do','Holy See (Vatican City State)','VA',8486)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (97,'Honduras','Honduras','HN',3450)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (98,'Hong Kong','Hong Kong','HK',3514)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (99,'Hungria',' Republica da','Hungary','HU',3557)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (100,'Islândia','Iceland','IS',3794)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (101,'Índia','India','IN',3611)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (102,'Indonésia','Indonesia','ID',3654)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (103,'Ira',' Republica Islâmica do','Iran (Islamic Republic of)','IR',3727)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (104,'Iraque','Iraq','IQ',3697)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (105,'Irlanda','Ireland','IE',3751)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (106,'Israel','Israel','IL',3832)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (107,'Itália','Italy','IT',3867)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (108,'Jamaica','Jamaica','JM',3913)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (109,'Japão','Japan','JP',3999)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (110,'Jordânia','Jordan','JO',4030)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (111,'Cazaquistão',' Republica do','Kazakhstan','KZ',1538)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (112,'Quênia','Kenya','KE',6238)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (113,'Kiribati','Kiribati','KI',4111)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (114,'Coreia',' Republica Popular Democrática da','Korea',' Democratic Peoples Republic of','KP',1872)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (115,'Coreia',' Republica da','Korea',' Republic of','KR',1902)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (116,'Kuwait','Kuwait','KW',1988)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (117,'Quirguiz',' Republica','Kyrgyzstan','KG',6254)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (118,'Laos',' Republica Popular Democrática do','Lao Peoples Democratic Republic','LA',4200)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (119,'Letônia',' Republica da','Latvia','LV',4278)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (120,'Líbano','Lebanon','LB',4316)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (121,'Lesoto','Lesotho','LS',4260)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (122,'Libéria','Liberia','LR',4340)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (123,'Líbia','Libyan Arab Jamahiriya','LY',4383)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (124,'Liechtenstein','Liechtenstein','LI',4405)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (125,'Lituânia',' Republica da','Lithuania','LT',4421)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (126,'Luxemburgo','Luxembourg','LU',4456)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (127,'Macau','Macau','MO',4472)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (128,'Macedônia do Norte','North Macedonia','MK',4499)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (129,'Madagascar','Madagascar','MG',4502)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (130,'Malavi','Malawi','MW',4588)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (131,'Malásia','Malaysia','MY',4553)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (132,'Maldivas','Maldives','MV',4618)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (133,'Mali','Mali','ML',4642)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (134,'Malta','Malta','MT',4677)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (135,'Marshall',' Ilhas','Marshall Islands','MH',4766)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (136,'Martinica','Martinique','MQ',4774)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (137,'Mauritânia','Mauritania','MR',4880)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (138,'Mauricio','Mauritius','MU',4855)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (139,'Mayotte (Ilhas Francesas)','Mayotte','YT',4885)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (140,'México','Mexico','MX',4936)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (141,'Micronesia','Micronesia',' Federated States of','FM',4995)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (142,'Moldávia',' Republica da','Moldova',' Republic of','MD',4944)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (143,'Mônaco','Monaco','MC',4952)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (144,'Mongólia','Mongolia','MN',4979)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (145,'Montserrat',' Ilhas','Montserrat','MS',5010)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (146,'Marrocos','Morocco','MA',4740)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (147,'Moçambique','Mozambique','MZ',5053)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (148,'Mianmar (Birmânia)','Myanmar','MM',930)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (149,'Namíbia','Namibia','NA',5070)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (150,'Nauru','Nauru','NR',5088)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (151,'Nepal','Nepal','NP',5177)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (152,'Países Baixos (Holanda)','Netherlands','NL',5738)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (154,'Nova Caledonia','New Caledonia','NC',5428)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (155,'Nova Zelândia','New Zealand','NZ',5487)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (156,'Nicarágua','Nicaragua','NI',5215)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (157,'Níger','Niger','NE',5258)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (158,'Nigéria','Nigeria','NG',5282)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (159,'Niue',' Ilha','Niue','NU',5312)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (160,'Norfolk',' Ilha','Norfolk Island','NF',5355)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (161,'Marianas do Norte','Northern Mariana Islands','MP',4723)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (162,'Noruega','Norway','NO',5380)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (163,'Oma','Oman','OM',5568)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (164,'Paquistão','Pakistan','PK',5762)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (165,'Palau','Palau','PW',5754)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (166,'Panamá','Panama','PA',5800)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (167,'Papua Nova Guine','Papua New Guinea','PG',5452)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (168,'Paraguai','Paraguay','PY',5860)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (169,'Peru','Peru','PE',5894)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (170,'Filipinas','Philippines','PH',2674)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (171,'Pitcairn',' Ilha','Pitcairn','PN',5932)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (172,'Polônia',' Republica da','Poland','PL',6033)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (173,'Portugal','Portugal','PT',6076)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (174,'Porto Rico','Puerto Rico','PR',6114)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (175,'Catar','Qatar','QA',1546)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (176,'Reunião',' Ilha','Reunion','RE',6602)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (177,'Romênia','Romania','RO',6700)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (178,'Rússia',' Federação da','Russian Federation','RU',6769)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (179,'Ruanda','Rwanda','RW',6750)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (180,'São Cristovão e Neves',' Ilhas','Saint Kitts and Nevis','KN',6955)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (181,'Santa Lucia','Saint LUCIA','LC',7153)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (182,'São Vicente e Granadinas','Saint Vincent and the Grenadines','VC',7056)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (183,'Samoa','Samoa','WS',6904)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (184,'San Marino','San Marino','SM',6971)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (185,'São Tome e Príncipe',' Ilhas','Sao Tome and Principe','ST',7200)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (186,'Arábia Saudita','Saudi Arabia','SA',531)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (187,'Senegal','Senegal','SN',7285)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (188,'Seychelles','Seychelles','SC',7315)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (189,'Serra Leoa','Sierra Leone','SL',7358)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (190,'Cingapura','Singapore','SG',7412)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (191,'Eslovaca',' Republica','Slovakia (Slovak Republic)','SK',2470)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (192,'Eslovênia',' Republica da','Slovenia','SI',2461)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (193,'Salomão',' Ilhas','Solomon Islands','SB',6777)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (194,'Somalia','Somalia','SO',7480)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (195,'África do Sul','South Africa','ZA',7560)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (196,'Ilhas Geórgia do Sul e Sandwich do Sul','South Georgia and the South Sandwich Islands','GS',2925)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (197,'Espanha','Spain','ES',2453)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (198,'Sri Lanka','Sri Lanka','LK',7501)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (199,'Santa Helena','St. Helena','SH',7102)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (200,'São Pedro e Miquelon','St. Pierre and Miquelon','PM',7005)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (201,'Sudão','Sudan','SD',7595)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (202,'Suriname','Suriname','SR',7706)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (203,'Svalbard e Jan Mayen','Svalbard and Jan Mayen Islands','SJ',7552)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (204,'Eswatini','Swaziland','SZ',7544)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (205,'Suécia','Sweden','SE',7641)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (206,'Suíça','Switzerland','CH',7676)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (207,'Síria',' Republica Árabe da','Syrian Arab Republic','SY',7447)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (208,'Formosa (Taiwan)','Taiwan',' Province of China','TW',1619)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (209,'Tadjiquistao',' Republica do','Tajikistan','TJ',7722)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (210,'Tanzânia',' Republica Unida da','Tanzania',' United Republic of','TZ',7803)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (211,'Tailândia','Thailand','TH',7765)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (212,'Togo','Togo','TG',8001)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (213,'Toquelau',' Ilhas','Tokelau','TK',8052)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (214,'Tonga','Tonga','TO',8109)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (215,'Trinidad e Tobago','Trinidad and Tobago','TT',8150)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (216,'Tunísia','Tunisia','TN',8206)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (217,'Turquia','Turkey','TR',8273)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (218,'Turcomenistão',' Republica do','Turkmenistan','TM',8249)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (219,'Turcas e Caicos',' Ilhas','Turks and Caicos Islands','TC',8230)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (220,'Tuvalu','Tuvalu','TV',8281)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (221,'Uganda','Uganda','UG',8338)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (222,'Ucrânia','Ukraine','UA',8311)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (223,'Emirados Árabes Unidos','United Arab Emirates','AE',2445)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (224,'Reino Unido','United Kingdom','GB',6289)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (225,'Estados Unidos','United States','US',2496)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (226,'Ilhas Menores Distantes dos Estados Unidos','United States Minor Outlying Islands','UM',18664)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (227,'Uruguai','Uruguay','UY',8451)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (228,'Uzbequistão',' Republica do','Uzbekistan','UZ',8478)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (229,'Vanuatu','Vanuatu','VU',5517)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (230,'Venezuela','Venezuela','VE',8508)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (231,'Vietnã','Viet Nam','VN',8583)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (232,'Virgens',' Ilhas (Britânicas)','Virgin Islands (British)','VG',8630)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (233,'Virgens',' Ilhas (E.U.A.)','Virgin Islands (U.S.)','VI',8664)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (234,'Wallis e Futuna',' Ilhas','Wallis and Futuna Islands','WF',8753)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (235,'Saara Ocidental','Western Sahara','EH',6858)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (236,'Iémen','Yemen','YE',3573)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (237,'Iugoslávia',' República Fed. da','Yugoslavia','YU',3883)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (238,'Zâmbia','Zambia','ZM',8907)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (239,'Zimbabue','Zimbabwe','ZW',6653)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (240,'Guernsey',' Ilha do Canal (Inclui Alderney e Sark)','Bailiwick of Guernsey','GG',1504)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (241,'Jersey',' Ilha do Canal','Bailiwick of Jersey','JE',1508)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (243,'Man',' Ilha de','Isle of Man','IM',3595)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (246,'Montenegro','Crna Gora (Montenegro)','ME',4985)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (247,'Republika Srbija','SÉRVIA','RS',7370)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (248,'Sudao do Sul','Republic of South Sudan','SS',7600)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (249,'Zona do Canal do Panamá','Zona del Canal de Panamá','NULL',8958)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (252,'Palestina','Dawlat Filas?in','PS',5780)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (253,'Aland',' Ilhas','Åland Islands','AX',153)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (255,'Curaçao','Curaçao','CW',200)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (256,'São Martinho',' Ilha de (Parte Holandesa)','Saint Martin','SM',6998)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (258,'Bonaire','Bonaire','AN',990)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (259,'Antartica','Antartica','AQ',420)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (260,'Ilha Herad e Ilhas Macdonald','Heard Island and McDonald Islands','AU',3433)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (261,'São Bartolomeu','Saint-Barthélemy','FR',6939)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (262,'São Martinho',' Ilha de (Parte Francesa)','Saint Martin','SM',6980)
insert into PAIS (pais_id, descricao, descricaoIngles, sigla, bacen) values (263,'Terras Austrais e Antárcticas Francesas','Terres Australes et Antarctiques Françaises','TF',7811)
